apiVersion: apps/v1
kind: Deployment
metadata:
  name: timestamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timestamp-app
  template:
    metadata:
      labels:
        app: timestamp-app
    spec:
      containers:
      - image: 888458450351.dkr.ecr.us-east-1.amazonaws.com/tf-timestamp-app-0:latest
        name: timestamp-app
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: timestamp-app
  labels:
    app: timestamp-app
spec:
  selector:
    app: timestamp-app
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP