version: 0.2
      
phases:

  # pre_build:
  #   commands:
  #     - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)

  build:
    commands:
      - docker build .

  post_build:
    commands:
      - echo "TODO push up the Docker image"
